### ISSUE TITLE
Allow measures to have microsegment-specific performance levels

### ISSUE THREAD

**Issue by trynthink** [trynthink/ptool2#24]
Currently, each measure can have only a single performance (e.g. IEER 20) or energy savings (e.g. 20%) level specified. Using output from EnergyPlus commercial building models, for measures that apply to commercial buildings, there will be data to support multiple performance or energy savings levels. There could be performance levels specified by climate zone, building type, and end use. 

The model should be able to support multiple performance levels at various levels of specificity. At a minimum, HVAC measures should be able to have separate performance levels if they apply to both heating and cooling (e.g. heat pumps).

**Comment by jtlangevin** [comment]
Ideally, we would allow the user to attach baseline and efficient performance levels to each of the microsegments that a measure applies to.  This should probably extend to cost as well (i.e., the capital cost of a NGHP microsegment technology baseline will be different than that of a GSHP microsegment technology baseline).

**Comment by trynthink** [comment]
After discussing this issue a little further, we need to provide/support the following data:

* baseline/incumbent cost
* baseline/incumbent absolute performance level
* efficient device cost
* efficient device absolute performance level

These could be specified by microsegment. For the baseline data, we should create a database that specifies the cost and performance for each microsegment, in a structure similar to the microsegments.json file. By specifying these levels uniformly for all microsegments, we reduce the risk of inconsistencies between measures in the same microsegment.

The efficient device cost and performance level should be specified within each measure, and for most measures, they will be single values, but for some measures (principally heating, cooling, and water heating), there might be further detail by climate zone and operating mode (heating or cooling). The measure database needs to be modified to support this structure for the data.

**Comment by jtlangevin** [comment]
The "run.py" routine currently accommodates microsegment-specific performance and cost levels for both the efficient measure and the baseline it is being compared against.  While the user will need to specify performance/cost for the measure, baseline performance/cost data are available for most microsegments from EIA, and will eventually be imported into "run.py" via a JSON file.  

Because the main issue of accommodating microsegment-specific performance/cost levels has been satisfied by "run.py", this issue can be closed.
